name: radx-harmonizer 

channels:
  - conda-forge
  - anaconda

dependencies:
  - python=3.11
  - jupyterlab
  - pandas
  - pandas-stubs
  - matplotlib
  - seaborn
  - isort
  - mypy
  - black
  - pylint
  - vulture
